language: scala


install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom

before_script:
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_42009c20f3b7_key -iv $encrypted_42009c20f3b7_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - ssh-add deploy_key

script: sbt test

before_deploy:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then sbt "release with-defaults skip-tests"; fi

