language: scala


install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom

before_script:
  - eval "$(ssh-agent -s)"
  - echo $DEPLOY_KEY > deploy_key
  - chmod 600 deploy_key
  - ssh-add deploy_key

script: sbt test

before_deploy:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then sbt "release with-defaults skip-tests"; fi

