language: scala

before_install:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - if [ "$AUTHOR_NAME" == "Travis CI User" ]; then echo "stopping"; exit 1; fi # abort the build if on travis

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom

before_script:
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_42009c20f3b7_key -iv $encrypted_42009c20f3b7_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - ssh-add deploy_key

script: sbt test

env:
  global:
    - secure:
       "mybLARJuXHfERl3MBG6bbPUPzuy2wT3pVayc1azi76+U+OEt6k06l8hcqNOSpMPXkXTmFqCpFssnRKLA4H29fChxnwvwSQAFGTHe70CXXXoMYQEd1jvTbLB+n1u1YHqn7AKHlcffDbQy/fCeZpKL3cY67F/fFCN97Bl38492eSlHF2FfZ18zT8Husp0EA7ud9hAcsXDlF9qrUTukZUfmK8GYS3tlzR4FsyReGVwA/T6/XJLW13mc9oa5UMif4BrDGKsa449WZbEIz6b8x5igY3BX1eUBlL8sMRkRkH6UVWh+t9ivhvYE9fqlebLTt7LRTeLpWTQRzao2Mp+HZwOjOUne2ZLzoemN0Fbyv06WDGM28V0U6BWby6wB/o7cxNESxCndX+WegRl6CPZUA2nfxZccd2c+1fwyIuq3/1mo7C25fCQAkHZ16U5PdphGJgpn0igedp2s0jv3SurYkqmoAJGarIBXy15sHA4PYUYn4oMXn1SGRv6pK4YWuENhxymQmzWP2udfAXeho4NNETvUfnGZQIh67gRto1V+zmwOQQIO07En6VozifLRDYer5fsoDKB7H4jjwTW7DutfzlKeJLu3NGDMrTVDcduH4hqbgYwEx2/8lRv/ftgSnS2gjlnD8PrsGWMOA83Qm4XnNOrPXL3y3ItvWpT8J7tNBTnGF4s="

before_deploy:
  - export VERSION_TAG="v`egrep -io '[0-9.]*' version.sbt`"
  - if [ "$TRAVIS_BRANCH" == "release" ]; then git remote set-url origin git@github.com:kszilagyi/pipeline-board.git; git checkout $TRAVIS_BRANCH; sbt "release with-defaults skip-tests"; fi


deploy:
  provider: releases
  api_key:
    secure:
      "Mc8RXgMvO4dcsFVrmRse4hr+7/5NNd4OIjkc//5tRiUQ4YW1KvM3gBrzbDuU8jjRWgO5aG6HSKTwY5s5xFhNoo0bZ3sVOpaMV/NE0I9jDD/VN8KgMQHoCe46qWR70D4mM+dPC9enansAeaKr07boczB4y1HqzcuCvp4H2SsI1HUW4pUynzyMhHMWbymo59ykmM2frZCkH+gdHOFc9oMwsijdBZZNR00h3LB5GwM/mMFyQap/66b2Mpj/5AdPpmcCMOS54LQVCZZddhfBcBB7V6njGdGCMh7P1PA7twLbrU195xAFdtfIwqVFr34R0K9W2wCAtqwxMfHx89SBYs2EF+Qzgf2+Ac+IG2pDcyIdSNSABxk/0aR6K34qPIxEDjkNEdCq23aqFdTjgDN5BJF7ety83AT2mr27/5P1BllyUPmM7Sqx1+szfvZLiqJtjvMzQSnfNspAwg9s5MGZYjX+rEGI6PCcReWMj8B82bbsOTXrf7zn7F79noXPjWECrqw146LXKOWtae6yskBgvnmdvBH6qhPt30FhfwLD4NDvfmGGaI0LSrpsz2KOYP0hm5XF9NDdlGI4fiS7KlpYFS7O6+jdzRAGprOtf9/+BLlqbm2rDRzgMX2zdWG9naDb3lx58qfIXr2vZ1IEyLTax7MQ1c7994nK2YA9KL46Xuj2p9Q="

  file_glob: true
  file: server/target/universal/server-*.zip
  on:
    repo: kszilagyi/pipeline-board
    branch: release
  tag_name: $VERSION_TAG
  skip-cleanup: true

