language: scala


install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom

before_script:
  - echo $DEPLOY_KEY > id_rsa
  - ssh-add id_rsa

script: sbt test

before_deploy:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then sbt "release with-defaults skip-tests"; fi

